# Generated by Django 2.1.7 on 2019-02-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainCoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=150, verbose_name='回复内容')),
            ],
            options={
                'verbose_name': '文章回评',
                'verbose_name_plural': '文章回评',
            },
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='com_photo',
            field=models.ImageField(default='default/tx3.jpg', max_length=200, upload_to='article/images', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MainCoreApp_Reply_related', to='MainCoreApp.ArticleComment', verbose_name='回复的评论'),
        ),
    ]
