# Generated by Django 2.1.7 on 2019-02-22 12:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainCoreApp', '0002_auto_20190221_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAdvertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='代码')),
                ('position', models.CharField(choices=[('left', '左边'), ('right', '右边')], max_length=5, verbose_name='位置')),
            ],
            options={
                'verbose_name': '添加广告',
                'verbose_name_plural': '添加广告',
            },
        ),
    ]
