# Generated by Django 2.1.7 on 2019-02-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainCoreApp', '0003_addadvertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websubnavset',
            name='nav_sort',
        ),
    ]
